name: Build and check links in PRs

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
      - name: Use Node.js 20.6.x
        uses: actions/setup-node@main
        with:
          node-version: 20.6.x
      - name: Build devchat website
        run: |
          npm install
          npm run build
