name: Build and check links in PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
      - name: Use Node.js 17.8.x
        uses: actions/setup-node@main
        with:
          node-version: 17.8.x
      - name: Build devchat website
        run: |
          npm install
          npm run build
